Bug fix for getHumString in myDHT.py - Fixed in the remaining Lessons.
>Error: NameError: global name 'humidity' is not defined

Fixed reference to use the getHum() function as output.

-
myMCP.py in all lessons had to change LUX_ADC to LUX_MCP

> def getLux(LUX_MCP):

I dont know much about this MCP, but I had to remove the gain=1, it was causing errors.